# test action
name: test action 2

on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'for testing'
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_KEY }}

      - name: Check out repository codes
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run 'npm clean-install'
        run: |
          cd testAction
          npm ci

      - name: testing
        uses: ./testAction/
        with:
          owner: ${{ inputs.owner }}
          token: ${{ steps.generate-token.outputs.token }}
