# test action
name: test action

on:
  workflow_dispatch:
    inputs:
      owner-name:
        description: 'for testing'
        required: true
        type: string

jobs:
  setup:
    if: inputs.owner-name
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: testing
        run: node testAction.js
