# test action
name: test action

on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'for testing'
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository codes
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run 'npm clean-install'
        run: |
          cd testAction
          npm ci

      - name: testing
        uses: ./testAction/
        with:
          owner: Not input
