# test action
name: test action

on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'for testing'
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository codes
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Run 'npm clean-install'
        run: npm ci

      - name: testing
        run: node testAction.js
        with:
          owner: ${{ inputs.owner }}
